/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: _ixed.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @_ixed: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly PassageMacros macros1;
	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros2;

	@_ixed()
	{
		this.StartPassage = "What are you?";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new PassageMacros() { Story = this };
		macros2 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
		passage29_Init();
		passage30_Init();
		passage31_Init();
		passage32_Init();
		passage33_Init();
		passage34_Init();
		passage35_Init();
		passage36_Init();
		passage37_Init();
		passage38_Init();
		passage39_Init();
		passage40_Init();
		passage41_Init();
		passage42_Init();
		passage43_Init();
		passage44_Init();
		passage45_Init();
		passage46_Init();
		passage47_Init();
		passage48_Init();
		passage49_Init();
		passage50_Init();
		passage51_Init();
		passage52_Init();
		passage53_Init();
		passage54_Init();
		passage55_Init();
		passage56_Init();
		passage57_Init();
		passage58_Init();
		passage59_Init();
		passage60_Init();
		passage61_Init();
		passage62_Init();
		passage63_Init();
		passage64_Init();
		passage65_Init();
		passage66_Init();
		passage67_Init();
		passage68_Init();
		passage69_Init();
		passage70_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: What are you?

	void passage1_Init()
	{
		this.Passages[@"What are you?"] = new StoryPassage(@"What are you?", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros1.image("Mixed/Alya_Smiling");
		yield return lineBreak();
		macros1.description("You are having a conversation with a friend who seems ethnically ambiguous and have been curious as to what is their heritage for quite some time...");
		yield return lineBreak();
		yield return text("What's up?");
		yield return lineBreak();
		yield return link("Your hair looks pretty, what are you mixed with?", "Your hair looks pretty, what are you mixed with?", null);
		yield return lineBreak();
		yield return link("Out of curiosity, what is your ethnicity?", "Out of curiosity, what is your ethnicity?", null);
		yield return lineBreak();
		yield return link("Nothing...", "Nothing...", null);
		yield break;
	}


	// .............
	// #2: Your hair looks pretty, what are you mixed with?

	void passage2_Init()
	{
		this.Passages[@"Your hair looks pretty, what are you mixed with?"] = new StoryPassage(@"Your hair looks pretty, what are you mixed with?", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("Thank you. But, what do you define as \"pretty\" hair?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You try to end the conversation, not knowing how to answer that", "You try to end the conversation, not knowing how to answer that", null);
		yield return lineBreak();
		yield return link("You know. Your hair is softer and not as dry as some other hair types", "You know. Your hair is softer and not as dry as some other hair types", null);
		yield break;
	}


	// .............
	// #3: You try to end the conversation, not knowing how to answer that

	void passage3_Init()
	{
		this.Passages[@"You try to end the conversation, not knowing how to answer that"] = new StoryPassage(@"You try to end the conversation, not knowing how to answer that", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Your friend probes you, asking \"Is some hair prettier than others?\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Yes", "Yes", null);
		yield return lineBreak();
		yield return link("Not really just your personal preference", "Not really just your personal preference", null);
		yield return lineBreak();
		yield return link("Of course", "Of course", null);
		yield break;
	}


	// .............
	// #4: You know. Your hair is softer and not as dry as some other hair types""

	void passage4_Init()
	{
		this.Passages[@"You know. Your hair is softer and not as dry as some other hair types"""] = new StoryPassage(@"You know. Your hair is softer and not as dry as some other hair types""", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend gets upset his voice starts to raise.");
		yield return lineBreak();
		yield return text("I...");
		yield return lineBreak();
		yield return link("Well, I mean...", "Well, I mean...", null);
		yield return lineBreak();
		yield return link("I'm sorry, tell me what what I said wrong.", "I'm sorry, tell me what what I said wrong.", null);
		yield break;
	}


	// .............
	// #5: Well, I mean...

	void passage5_Init()
	{
		this.Passages[@"Well, I mean..."] = new StoryPassage(@"Well, I mean...", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		macros1.description("Your friend is furious.");
		yield return lineBreak();
		yield return text("So coarse hair is bad?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No... Just not as pretty", "No... Just not as pretty", null);
		yield return lineBreak();
		yield return link("Uhhh... yea.", "Uhhh... yea.", null);
		yield break;
	}


	// .............
	// #6: I'm sorry, tell me what what I said wrong.

	void passage6_Init()
	{
		this.Passages[@"I'm sorry, tell me what what I said wrong."] = new StoryPassage(@"I'm sorry, tell me what what I said wrong.", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("She shrugs...");
		yield return lineBreak();
		yield return text("I don't feel like I should have to explain this to you.");
		yield break;
	}


	// .............
	// #7: Just black? Your loose curls make you look a little more exotic though.

	void passage7_Init()
	{
		this.Passages[@"Just black? Your loose curls make you look a little more exotic though."] = new StoryPassage(@"Just black? Your loose curls make you look a little more exotic though.", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend seems upset.");
		yield return lineBreak();
		yield return text("What do you mean by exotic?");
		yield return lineBreak();
		yield return link("You know, it's different", "You know, it's different", null);
		yield return lineBreak();
		yield return link("It's not like other black people's hair", "It's not like other black people's hair", null);
		yield break;
	}


	// .............
	// #8: Okay, I was just curious.

	void passage8_Init()
	{
		this.Passages[@"Okay, I was just curious."] = new StoryPassage(@"Okay, I was just curious.", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		macros1.description("Your friend seems disappointed");
		yield return lineBreak();
		yield return text("I'm black, but people call me mixed because my parents come from two different parts of Africa with different skin tones and hair textures. Did I blow your mind?");
		yield return lineBreak();
		yield return link("You did.", "You did.", null);
		yield break;
	}


	// .............
	// #9: Yes

	void passage9_Init()
	{
		this.Passages[@"Yes"] = new StoryPassage(@"Yes", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		macros1.description("Is your friend being sarcastic?");
		yield return lineBreak();
		yield return text("So what would make some hair prettier than others?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Length of hair", "Length of hair", null);
		yield return lineBreak();
		yield return link("Softness", "Softness", null);
		yield return lineBreak();
		yield return link("Straightness", "Straightness", null);
		yield return lineBreak();
		yield return link("Kinkiness", "Kinkiness", null);
		yield return lineBreak();
		yield return link("Color", "Color", null);
		yield break;
	}


	// .............
	// #10: Not really just your personal preference

	void passage10_Init()
	{
		this.Passages[@"Not really just your personal preference"] = new StoryPassage(@"Not really just your personal preference", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		macros1.description("Your friend seems kind of annoyed");
		yield return lineBreak();
		yield return text("But why do you prefer certain kinds of hair?");
		yield return lineBreak();
		yield return link("Because some is softer and just looks better", "Because some is softer and just looks better", null);
		yield return lineBreak();
		yield return link("You don't know", "You don't know", null);
		yield return lineBreak();
		yield return link("You just do", "You just do", null);
		yield break;
	}


	// .............
	// #11: Because some is softer and just looks better

	void passage11_Init()
	{
		this.Passages[@"Because some is softer and just looks better"] = new StoryPassage(@"Because some is softer and just looks better", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("So you're equivocating softer to better?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Umm... yes", "Umm... yes", null);
		yield return lineBreak();
		yield return link("No, just your preference", "No, just your preference", null);
		yield break;
	}


	// .............
	// #12: You don't know

	void passage12_Init()
	{
		this.Passages[@"You don't know"] = new StoryPassage(@"You don't know", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend looks upset");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #13: You just do

	void passage13_Init()
	{
		this.Passages[@"You just do"] = new StoryPassage(@"You just do", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend is upset");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #14: Length of hair

	void passage14_Init()
	{
		this.Passages[@"Length of hair"] = new StoryPassage(@"Length of hair", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #15: Softness

	void passage15_Init()
	{
		this.Passages[@"Softness"] = new StoryPassage(@"Softness", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #16: Straightness

	void passage16_Init()
	{
		this.Passages[@"Straightness"] = new StoryPassage(@"Straightness", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #17: Kinkiness

	void passage17_Init()
	{
		this.Passages[@"Kinkiness"] = new StoryPassage(@"Kinkiness", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #18: Color

	void passage18_Init()
	{
		this.Passages[@"Color"] = new StoryPassage(@"Color", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #19: Of course

	void passage19_Init()
	{
		this.Passages[@"Of course"] = new StoryPassage(@"Of course", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("Of course? So what makes some hair look better?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You can't identify certain traits", "You can't identify certain traits", null);
		yield return lineBreak();
		yield return link("The texture, style, length of hair, etc.", "The texture, style, length of hair, etc.", null);
		yield break;
	}


	// .............
	// #20: You can't identify certain traits

	void passage20_Init()
	{
		this.Passages[@"You can't identify certain traits"] = new StoryPassage(@"You can't identify certain traits", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost her patience.");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #21: The texture, style, length of hair, etc.

	void passage21_Init()
	{
		this.Passages[@"The texture, style, length of hair, etc."] = new StoryPassage(@"The texture, style, length of hair, etc.", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend has lost her patience.");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("Think about some of the reasons why certain hair types may be deemed better by your standards. A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #22: Umm... yes

	void passage22_Init()
	{
		this.Passages[@"Umm... yes"] = new StoryPassage(@"Umm... yes", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("You do realize that you are somewhat implying that African-american hair, which isn't usually deemed as 'soft', isn't as good as less coarse hair?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No that's not what I'm saying!", "No that's not what I'm saying!", null);
		yield return lineBreak();
		yield return link("Umm...", "Umm...", null);
		yield break;
	}


	// .............
	// #23: No, just your preference

	void passage23_Init()
	{
		this.Passages[@"No, just your preference"] = new StoryPassage(@"No, just your preference", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		macros1.description("Your curiosity is piqued");
		yield return lineBreak();
		yield return text("Okay, I can live with a personal preference, but did you know a lot of times the reason we like certain hair types is because of Eurocentric ideals?");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield break;
	}


	// .............
	// #24: No that's not what I'm saying!

	void passage24_Init()
	{
		this.Passages[@"No that's not what I'm saying!"] = new StoryPassage(@"No that's not what I'm saying!", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend seems upset, but you seemed to learn something.");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("That's not what you're saying but by virtue of the fact that you prefer a certain hair type, means that you may have certain biases. A lot of times the reason we like certain hair types is because of Eurocentric ideals. ");
		yield break;
	}


	// .............
	// #25: Umm...

	void passage25_Init()
	{
		this.Passages[@"Umm..."] = new StoryPassage(@"Umm...", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend seems upset");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #26: No... Just not as pretty

	void passage26_Init()
	{
		this.Passages[@"No... Just not as pretty"] = new StoryPassage(@"No... Just not as pretty", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("You do realize you're technically saying black hair isn't pretty right?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That's not what I said", "That's not what I said", null);
		yield return lineBreak();
		yield return link("How so?", "How so?", null);
		yield break;
	}


	// .............
	// #27: Uhhh... yea.

	void passage27_Init()
	{
		this.Passages[@"Uhhh... yea."] = new StoryPassage(@"Uhhh... yea.", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		yield return text("So black hair is bad?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("That's not what I said though", "That's not what I said though", null);
		yield return lineBreak();
		yield return link("How does that even add up?", "How does that even add up?", null);
		yield return lineBreak();
		yield return link("No... just not my personal favorite", "No... just not my personal favorite", null);
		yield break;
	}


	// .............
	// #28: That's not what I said

	void passage28_Init()
	{
		this.Passages[@"That's not what I said"] = new StoryPassage(@"That's not what I said", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("You didn't say it directly but I'm sure you know black hair is coarser than certain hair types.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Well...that's not the reason.", "Well...that's not the reason.", null);
		yield return lineBreak();
		yield return link("Oh, I'm sorry if it came across that way", "Oh, I'm sorry if it came across that way", null);
		yield break;
	}


	// .............
	// #29: How so?

	void passage29_Init()
	{
		this.Passages[@"How so?"] = new StoryPassage(@"How so?", new string[]{  }, passage29_Main);
	}

	IStoryThread passage29_Main()
	{
		macros1.description("Your friend has lost their patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #30: Well...that's not the reason.

	void passage30_Init()
	{
		this.Passages[@"Well...that's not the reason."] = new StoryPassage(@"Well...that's not the reason.", new string[]{  }, passage30_Main);
	}

	IStoryThread passage30_Main()
	{
		macros1.description("Your friend has lost her patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("You're missing the point. A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #31: Oh, I'm sorry if it came across that way

	void passage31_Init()
	{
		this.Passages[@"Oh, I'm sorry if it came across that way"] = new StoryPassage(@"Oh, I'm sorry if it came across that way", new string[]{  }, passage31_Main);
	}

	IStoryThread passage31_Main()
	{
		macros1.description("You've tested your friend's patience");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/,","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("I know you never meant bad by it but maybe you should do some research.");
		yield break;
	}


	// .............
	// #32: That's not what I said though

	void passage32_Init()
	{
		this.Passages[@"That's not what I said though"] = new StoryPassage(@"That's not what I said though", new string[]{  }, passage32_Main);
	}

	IStoryThread passage32_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("You definitely have a lot of work ahead of you on fixing this relationship");
		yield return lineBreak();
		yield return text("You never said it directly but that's what you're implying.");
		yield break;
	}


	// .............
	// #33: You know, it's different

	void passage33_Init()
	{
		this.Passages[@"You know, it's different"] = new StoryPassage(@"You know, it's different", new string[]{  }, passage33_Main);
	}

	IStoryThread passage33_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		yield return text("Okay, then say different, why say exotic?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What's wrong with saying exotic?", "What's wrong with saying exotic?", null);
		yield return lineBreak();
		yield return link("How is exotic a bad thing?", "How is exotic a bad thing?", null);
		yield break;
	}


	// .............
	// #34: It's not like other black people's hair

	void passage34_Init()
	{
		this.Passages[@"It's not like other black people's hair"] = new StoryPassage(@"It's not like other black people's hair", new string[]{  }, passage34_Main);
	}

	IStoryThread passage34_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("What's that supposed to mean???");
		yield return lineBreak();
		yield return link("Black people have coarser hair...", "Black people have coarser hair...", null);
		yield return lineBreak();
		yield return link("It just looks better", "It just looks better", null);
		yield break;
	}


	// .............
	// #35: What's wrong with saying exotic?

	void passage35_Init()
	{
		this.Passages[@"What's wrong with saying exotic?"] = new StoryPassage(@"What's wrong with saying exotic?", new string[]{  }, passage35_Main);
	}

	IStoryThread passage35_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("When people describe me as exotic it implies that I'm not from here, and you know how some people feel about people who are not from here.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("No I don't actually", "No I don't actually", null);
		yield return lineBreak();
		yield return link("Okay, I'll do better next time", "Okay, I'll do better next time", null);
		yield break;
	}


	// .............
	// #36: How is exotic a bad thing?

	void passage36_Init()
	{
		this.Passages[@"How is exotic a bad thing?"] = new StoryPassage(@"How is exotic a bad thing?", new string[]{  }, passage36_Main);
	}

	IStoryThread passage36_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend is upset");
		yield return lineBreak();
		yield return text("First of all, I'm not some object, secondly, you're implying I'm not from here by calling me exotic.");
		yield return lineBreak();
		yield return link("I wasn't objectifying you", "I wasn't objectifying you", null);
		yield return lineBreak();
		yield return link("How am I implying you're not from here?", "How am I implying you're not from here?", null);
		yield break;
	}


	// .............
	// #37: Black people have coarser hair...

	void passage37_Init()
	{
		this.Passages[@"Black people have coarser hair..."] = new StoryPassage(@"Black people have coarser hair...", new string[]{  }, passage37_Main);
	}

	IStoryThread passage37_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		yield return text("So you're saying black people don't have pretty hair.");
		yield return lineBreak();
		yield return link("Some do", "Some do", null);
		yield return lineBreak();
		yield return link("If you wanna say it like that, then I guess", "If you wanna say it like that, then I guess", null);
		yield break;
	}


	// .............
	// #38: It just looks better

	void passage38_Init()
	{
		this.Passages[@"It just looks better"] = new StoryPassage(@"It just looks better", new string[]{  }, passage38_Main);
	}

	IStoryThread passage38_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("Have you ever thought about why?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Not really", "Not really", null);
		yield return lineBreak();
		yield return link("Why would I?", "Why would I?", null);
		yield break;
	}


	// .............
	// #39: No I don't actually

	void passage39_Init()
	{
		this.Passages[@"No I don't actually"] = new StoryPassage(@"No I don't actually", new string[]{  }, passage39_Main);
	}

	IStoryThread passage39_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("Really? A lot of people see immigrants or people who look like immigrants as bad. You should do some research.");
		yield return lineBreak();
		macros1.links("https://everydayfeminism.com/2016/01/calling-woc-exotic-is-racist");
		yield break;
	}


	// .............
	// #40: Okay, I'll do better next time

	void passage40_Init()
	{
		this.Passages[@"Okay, I'll do better next time"] = new StoryPassage(@"Okay, I'll do better next time", new string[]{  }, passage40_Main);
	}

	IStoryThread passage40_Main()
	{
		macros1.image("Mixed/Alya_Smiling");
		yield return lineBreak();
		yield return text("Alright, cool.");
		yield return lineBreak();
		macros1.links("https://everydayfeminism.com/2016/01/calling-woc-exotic-is-racist");
		yield break;
	}


	// .............
	// #41: I wasn't objectifying you

	void passage41_Init()
	{
		this.Passages[@"I wasn't objectifying you"] = new StoryPassage(@"I wasn't objectifying you", new string[]{  }, passage41_Main);
	}

	IStoryThread passage41_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		yield return text("Maybe not deliberately, but exotic is normally used to describe objects, not people.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Okay I'll choose my words more carefully", "Okay I'll choose my words more carefully", null);
		yield return lineBreak();
		yield return link("You take everything so seriously", "You take everything so seriously", null);
		yield break;
	}


	// .............
	// #42: How am I implying you're not from here?

	void passage42_Init()
	{
		this.Passages[@"How am I implying you're not from here?"] = new StoryPassage(@"How am I implying you're not from here?", new string[]{  }, passage42_Main);
	}

	IStoryThread passage42_Main()
	{
		yield return text("Exotic literally means just that!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Come on, let's not argue semantics", "Come on, let's not argue semantics", null);
		yield return lineBreak();
		yield return link("But that's not what I meant", "But that's not what I meant", null);
		yield break;
	}


	// .............
	// #43: Okay I'll choose my words more carefully

	void passage43_Init()
	{
		this.Passages[@"Okay I'll choose my words more carefully"] = new StoryPassage(@"Okay I'll choose my words more carefully", new string[]{  }, passage43_Main);
	}

	IStoryThread passage43_Main()
	{
		macros1.description("Your friend is clearly upset");
		yield return lineBreak();
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.links("https://everydayfeminism.com/2016/01/calling-woc-exotic-is-racist");
		yield return lineBreak();
		yield return text("I gotta go now, I'm late for class.");
		yield break;
	}


	// .............
	// #44: You take everything so seriously

	void passage44_Init()
	{
		this.Passages[@"You take everything so seriously"] = new StoryPassage(@"You take everything so seriously", new string[]{  }, passage44_Main);
	}

	IStoryThread passage44_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("What??? I'm late for class I have no time for this.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Of course you are", "Of course you are", null);
		yield return lineBreak();
		yield return link("Hey, I never meant it as a bad thing", "Hey, I never meant it as a bad thing", null);
		yield break;
	}


	// .............
	// #45: Of course you are

	void passage45_Init()
	{
		this.Passages[@"Of course you are"] = new StoryPassage(@"Of course you are", new string[]{  }, passage45_Main);
	}

	IStoryThread passage45_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		macros1.description("You just lost a friend");
		yield return lineBreak();
		yield return text("Yo, stop talking to me bro.");
		yield break;
	}


	// .............
	// #46: Hey, I never meant it as a bad thing

	void passage46_Init()
	{
		this.Passages[@"Hey, I never meant it as a bad thing"] = new StoryPassage(@"Hey, I never meant it as a bad thing", new string[]{  }, passage46_Main);
	}

	IStoryThread passage46_Main()
	{
		macros1.image("Mixed/Alya_Walking_Away");
		yield return lineBreak();
		macros1.description("She starts to walk away. Why would she?");
		yield return lineBreak();
		yield return text("You may not but it is!");
		yield break;
	}


	// .............
	// #47: Talk her down

	void passage47_Init()
	{
		this.Passages[@"Talk her down"] = new StoryPassage(@"Talk her down", new string[]{  }, passage47_Main);
	}

	IStoryThread passage47_Main()
	{
		yield return text("\"What are you doing!? Back off.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("By now people start to look and your friend Deandre steps in: \"Is everything okay here?\"");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Yea, it's fine", "Yea, it's fine", null);
		yield return lineBreak();
		yield return link("Just walk away", "Just walk away", null);
		yield return lineBreak();
		yield return link("She's being a little softie", "She's being a little softie", null);
		yield break;
	}


	// .............
	// #48: Try to talk to her after

	void passage48_Init()
	{
		this.Passages[@"Try to talk to her after"] = new StoryPassage(@"Try to talk to her after", new string[]{  }, passage48_Main);
	}

	IStoryThread passage48_Main()
	{
		macros1.description("She refuses to reply to any of your messages and is actively ignoring you.");
		yield break;
	}


	// .............
	// #49: Do nothing

	void passage49_Init()
	{
		this.Passages[@"Do nothing"] = new StoryPassage(@"Do nothing", new string[]{  }, passage49_Main);
	}

	IStoryThread passage49_Main()
	{
		yield return text("You don't here from her in days, and she ignoes all your texts. You should probably read this then.");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #50: Yea, it's fine

	void passage50_Init()
	{
		this.Passages[@"Yea, it's fine"] = new StoryPassage(@"Yea, it's fine", new string[]{  }, passage50_Main);
	}

	IStoryThread passage50_Main()
	{
		yield break;
	}


	// .............
	// #51: Just walk away

	void passage51_Init()
	{
		this.Passages[@"Just walk away"] = new StoryPassage(@"Just walk away", new string[]{  }, passage51_Main);
	}

	IStoryThread passage51_Main()
	{
		yield break;
	}


	// .............
	// #52: She's being a little softie

	void passage52_Init()
	{
		this.Passages[@"She's being a little softie"] = new StoryPassage(@"She's being a little softie", new string[]{  }, passage52_Main);
	}

	IStoryThread passage52_Main()
	{
		yield break;
	}


	// .............
	// #53: Come on, let's not argue semantics

	void passage53_Init()
	{
		this.Passages[@"Come on, let's not argue semantics"] = new StoryPassage(@"Come on, let's not argue semantics", new string[]{  }, passage53_Main);
	}

	IStoryThread passage53_Main()
	{
		yield return text("It's not just semantics! Words have power and it would affect certain people.");
		yield return lineBreak();
		macros1.links("https://everydayfeminism.com/2016/01/calling-woc-exotic-is-racist");
		yield break;
	}


	// .............
	// #54: But that's not what I meant

	void passage54_Init()
	{
		this.Passages[@"But that's not what I meant"] = new StoryPassage(@"But that's not what I meant", new string[]{  }, passage54_Main);
	}

	IStoryThread passage54_Main()
	{
		yield return text("\"You may not have meant it but that's why you need to be more careful with your words. Read this.\"");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #55: Some do

	void passage55_Init()
	{
		this.Passages[@"Some do"] = new StoryPassage(@"Some do", new string[]{  }, passage55_Main);
	}

	IStoryThread passage55_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("Well that's problematic!");
		yield return lineBreak();
		yield return link("How?", "How?", null);
		yield return lineBreak();
		yield return link("I don't think so", "I don't think so", null);
		yield break;
	}


	// .............
	// #56: If you wanna say it like that, then I guess

	void passage56_Init()
	{
		this.Passages[@"If you wanna say it like that, then I guess"] = new StoryPassage(@"If you wanna say it like that, then I guess", new string[]{  }, passage56_Main);
	}

	IStoryThread passage56_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend is visibly upset");
		yield return lineBreak();
		yield return text("That's so messed up. Stop talking to me dude.");
		yield break;
	}


	// .............
	// #57: How?

	void passage57_Init()
	{
		this.Passages[@"How?"] = new StoryPassage(@"How?", new string[]{  }, passage57_Main);
	}

	IStoryThread passage57_Main()
	{
		macros1.description("Your friend walks away");
		yield return lineBreak();
		macros1.image("Mixed/Alya_Walking_Away");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield break;
	}


	// .............
	// #58: I don't think so

	void passage58_Init()
	{
		this.Passages[@"I don't think so"] = new StoryPassage(@"I don't think so", new string[]{  }, passage58_Main);
	}

	IStoryThread passage58_Main()
	{
		macros1.image("Mixed/Alya_Walking_Away");
		yield return lineBreak();
		macros1.description("Your friend walks away");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield break;
	}


	// .............
	// #59: Not really

	void passage59_Init()
	{
		this.Passages[@"Not really"] = new StoryPassage(@"Not really", new string[]{  }, passage59_Main);
	}

	IStoryThread passage59_Main()
	{
		macros1.description("Your friend is upset");
		yield return lineBreak();
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("Think about this: a lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #60: Why would I?

	void passage60_Init()
	{
		this.Passages[@"Why would I?"] = new StoryPassage(@"Why would I?", new string[]{  }, passage60_Main);
	}

	IStoryThread passage60_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		yield return text("So you just say and feel things without ever questioning them?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Is that an issue?", "Is that an issue?", null);
		yield return lineBreak();
		yield return link("Overthinking isn't good", "Overthinking isn't good", null);
		yield break;
	}


	// .............
	// #61: Is that an issue?

	void passage61_Init()
	{
		this.Passages[@"Is that an issue?"] = new StoryPassage(@"Is that an issue?", new string[]{  }, passage61_Main);
	}

	IStoryThread passage61_Main()
	{
		macros1.description("You didn't realize your friend would react this way");
		yield return lineBreak();
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		yield return text("Yes, yes it is! Words have power. What you do and say can affect people in so many ways!");
		yield break;
	}


	// .............
	// #62: Overthinking isn't good

	void passage62_Init()
	{
		this.Passages[@"Overthinking isn't good"] = new StoryPassage(@"Overthinking isn't good", new string[]{  }, passage62_Main);
	}

	IStoryThread passage62_Main()
	{
		macros1.image("Mixed/Alya_Listening");
		yield return lineBreak();
		macros1.description("Your friend seems a bit exhausted");
		yield return lineBreak();
		yield return text("Yea, but not thinking at all is worse.");
		yield break;
	}


	// .............
	// #63: Out of curiosity, what is your ethnicity?

	void passage63_Init()
	{
		this.Passages[@"Out of curiosity, what is your ethnicity?"] = new StoryPassage(@"Out of curiosity, what is your ethnicity?", new string[]{  }, passage63_Main);
	}

	IStoryThread passage63_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		macros1.description("Your friend seems a little confused");
		yield return lineBreak();
		yield return text("I'm black");
		yield return lineBreak();
		yield return link("Just black? Your loose curls make you look a little more exotic though.", "Just black? Your loose curls make you look a little more exotic though.", null);
		yield return lineBreak();
		yield return link("Okay, I was just curious.", "Okay, I was just curious.", null);
		yield break;
	}


	// .............
	// #64: Nothing...

	void passage64_Init()
	{
		this.Passages[@"Nothing..."] = new StoryPassage(@"Nothing...", new string[]{  }, passage64_Main);
	}

	IStoryThread passage64_Main()
	{
		macros1.image("Mixed/Alya_Mid_Sentence");
		yield return lineBreak();
		macros1.description("They never tell you. And that's okay. Why does their ethnicity matter?");
		yield return lineBreak();
		yield return text("Coffee?");
		yield return lineBreak();
		yield return link("Sure", "Sure", null);
		yield return lineBreak();
		yield return link("No thanks, I've got class", "No thanks, I've got class", null);
		yield break;
	}


	// .............
	// #65: Sure

	void passage65_Init()
	{
		this.Passages[@"Sure"] = new StoryPassage(@"Sure", new string[]{  }, passage65_Main);
	}

	IStoryThread passage65_Main()
	{
		macros1.image("Mixed/Alya_Smiling");
		yield return lineBreak();
		macros1.description("Coffee sounds good...");
		yield return lineBreak();
		yield return text("Cool, let's hit up that new place. I hear they make an amazing latte!");
		yield break;
	}


	// .............
	// #66: No thanks, I've got class

	void passage66_Init()
	{
		this.Passages[@"No thanks, I've got class"] = new StoryPassage(@"No thanks, I've got class", new string[]{  }, passage66_Main);
	}

	IStoryThread passage66_Main()
	{
		macros1.image("Mixed/Alya_Smiling");
		yield return lineBreak();
		macros1.description("So much to do, so little time...");
		yield return lineBreak();
		yield return text("Alright, I'll catch you later.");
		yield break;
	}


	// .............
	// #67: How does that even add up?

	void passage67_Init()
	{
		this.Passages[@"How does that even add up?"] = new StoryPassage(@"How does that even add up?", new string[]{  }, passage67_Main);
	}

	IStoryThread passage67_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("You feel you've lost a good friend...");
		yield return lineBreak();
		yield return text("By saying coarse hair is bad you are saying people with coarse hair have bad hair...like, I don't know, black people!");
		yield break;
	}


	// .............
	// #68: No... just not my personal favorite

	void passage68_Init()
	{
		this.Passages[@"No... just not my personal favorite"] = new StoryPassage(@"No... just not my personal favorite", new string[]{  }, passage68_Main);
	}

	IStoryThread passage68_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend is upset.");
		yield return lineBreak();
		macros1.links("http://www.germmagazine.com/eurocentric-beauty-standards-a-global-disease/","https://curltalk.naturallycurly.com/discussion/82744/why-isnt-curly-hair-seen-as-attractive-as-straight-hair");
		yield return lineBreak();
		yield return text("A lot of times the reason we like certain hair types is because of Eurocentric ideals.");
		yield break;
	}


	// .............
	// #69: You did.

	void passage69_Init()
	{
		this.Passages[@"You did."] = new StoryPassage(@"You did.", new string[]{  }, passage69_Main);
	}

	IStoryThread passage69_Main()
	{
		macros1.image("Mixed/Alya_Upset");
		yield return lineBreak();
		macros1.description("Your friend gets really serious");
		yield return lineBreak();
		yield return text("Real talk. If I didn't explain that to you, you should be totally cool with that. No one owes you an explanation about their ethnicity.");
		yield break;
	}


	// .............
	// #70: You know. Your hair is softer and not as dry as some other hair types

	void passage70_Init()
	{
		this.Passages[@"You know. Your hair is softer and not as dry as some other hair types"] = new StoryPassage(@"You know. Your hair is softer and not as dry as some other hair types", new string[]{  }, passage70_Main);
	}

	IStoryThread passage70_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}